replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/devops-project/app-repo/rick-and-morty-app
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: chart-backend.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

env:
  PORT: "8080"
  GCP_PROJECT_ID: "devops-project"
  GCP_REGION: "us-central1"
